---
- name: Развертывание Callcenter на базе Asterisk и Ubuntu 22
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes

  tasks:
    - name: Установка Asterisk
      ansible.builtin.apt:
        name:
          - asterisk
        state: present

    - name: Активация и запуск Asterisk
      ansible.builtin.service:
        name: asterisk
        state: started
        enabled: yes

    - name: Копирование extensions.conf
      copy:
        src: conf/extensions.conf
        dest: /etc/asterisk/extensions.conf
        mode: '0644'
        
    - name: Копирование pjsip.conf
      copy:
        src: conf/pjsip.conf
        dest: /etc/asterisk/pjsip.conf
        mode: '0644'
        
    - name: Копирование queues.conf
      copy:
        src: conf/queues.conf
        dest: /etc/asterisk/queues.conf
        mode: '0644'
        
    - name: Копирование musiconhold.conf
      copy:
        src: conf/musiconhold.conf
        dest: /etc/asterisk/musiconhold.conf
        mode: '0644'
        
    - name: Копирование moh.wav
      copy:
        src: conf/moh.wav
        dest: /var/lib/asterisk/moh/moh.wav
        mode: '0644'

  handlers:
    - name: Перезагрузка Asterisk
      ansible.builtin.service:
        name: asterisk
        state: reloaded
